#ifndef MESHDEMOCUSERTYPES_H
#define MESHDEMOCUSERTYPES_H

#define TOKEN_USER_TYPE_POST 4
#define TOKEN_USER_TYPE_VOTE 5
#define TOKEN_USER_TYPE_TOPIC 6
#define TOKEN_USER_TYPE_POST_MOD 7
#define TOKEN_USER_TYPE_POST_RANKINGS 8
#define TOKEN_USER_TYPE_SUBSCRIBE_CHANGE 9

#endif // MESHDEMOCUSERTYPES_H
